name: KPSS Otomatik Scraper

on:
  schedule:
    - cron: '*/30 * * * *' # Her 30 dakikada bir otomatik çalışır
  workflow_dispatch: # Elle tetiklemek için

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: |
          pip install -r requirements.txt

      - name: Robotu Çalıştır
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python scraper.py
